- name: ansible command vs shell module
  hosts: local
  connection: local
  tasks:
  - name: command module test
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output

  - name: print users output
    ansible.builtin.debug:
      msg: "{{ users_output }}"

  - name: command module test
    ansible.builtin.shell: ls-lrt > file.txt
    register: users_output